### PR TITLE
Extend Prisma sample

### PR DESCRIPTION
**Pull request by tak1n**
Introduced a relationship (owner has many cats), also added a custom class-validator rule/check which accesses the database through prisma service and therefore has access to the Nest DI container through `useContainer`.

### CODE REVIEW

**Comment by jmcdo29** [comment]
Overall it looks great! Thanks for adding this in. Almost wish it was a separate "app", but I think it'll be fine like this.

**Comment by tak1n** [comment]
> Overall it looks great! Thanks for adding this in. Almost wish it was a separate "app", but I think it'll be fine like this.

Sure I can also split it up if you like. The new app should also use prisma or no DB/ORM at all and just showcase how to use NestJS DI in custom class-validator rules?

**Comment by jmcdo29** [comment]
> > Overall it looks great! Thanks for adding this in. Almost wish it was a separate "app", but I think it'll be fine like this.
> 
> Sure I can also split it up if you like. The new app should also use prisma or no DB/ORM at all and just showcase how to use NestJS DI in custom class-validator rules?

Generally I'd prefer no ORM/DB attached to it, to just give a raw example and let devs tie the ideas together. Everything in Nest is pretty much just building blocks and knowing how to glue them together. This is one of those moments of showing the glue (using both custom validator and prisma), but it may be a useful example to keep as is

**Comment by jmcdo29** [comment]
I'm gonna go ahead and merge this. If you have the time/patience/energy for another PR that demonstrates _just_ the custom validator that would be awesome.

**Comment by tak1n** [comment]
> I'm gonna go ahead and merge this. If you have the time/patience/energy for another PR that demonstrates _just_ the custom validator that would be awesome.

Sure, will take a look at it the next few days.

Thx for merging 😃

**Pull request merged**
