### PR TITLE
refactor: return types in mock functions for strict type checks

### PR DESCRIPTION
**Pull request by neerajkumar161**
- refactored strict types checks in ```cat.controller.spec.ts``` in mongo-sample
- removed any type annotation in ```cat.service.ts``` in mongo-sample

### CODE REVIEW

**Comment by neerajkumar161** [comment]
Hey collaborators, let me know if this refactor is correct or not. If it is, we can refactor other unit tests as well.

**Comment by jmcdo29** [comment]
Nice, tests pass and I think it all looks alright. Feel free to either open a new PR for the others, or modify this one (if modifying this one let me know so I don't merge it too early)

**Comment by neerajkumar161** [comment]
@jmcdo29 Awesome 🤩. I will create different PRs for different test files. Is it okay?

**Comment by jmcdo29** [comment]
Yeah that works

**Pull request merged**
