### PR TITLE
E2E Tests Setup

### LINKED ISSUE #354: [NEW TEST] Automated E2E Testing
Use Dockerfiles and `docker-compose` to allow for E2E tests to be run via GitHub Actions. This will allow for even better tracking of changes to the NestJS Ecosystem and will help others know the E2E tests are working properly

### PR DESCRIPTION
**Pull request by malcolm-kee**
resolves #354 

I come up with initial setup so that it's easier to continue the discussion.

@jmcdo29  feel free to improve/revamp the whole convention here as I feel like it's a bit complex now, but I not sure how to simplify it.

### CODE REVIEW

**Comment by jmcdo29** [comment]
Looking pretty good. I think running the two applications is fine, especially because A) we're already in a monorepo, and B) it's a microservice, you need multiple applications. 

The thing that concerns me the most is that we have the publisher sending off a message and then returning `true` without waiting for a response from the server. Is there a chance there could be an error and it isn't be propagated and/or tested? Is there some way we can fix that? Have the `publisher` be a mix of `HTTP` and sending the events and have the `subscriber` be only for receiving the messages?

**Comment by malcolm-kee** [comment]
I've fixed the publisher emitting code to handle error.

Regarding the subscriber as only receiving message, at the moment I added a REST endpoint and database to it so that I can make assertion that it receives data. Do you have any alternative of assertion that I can make?

**Comment by jmcdo29** [comment]
> Regarding the subscriber as only receiving message, at the moment I added a REST endpoint and database to it so that I can make assertion that it receives data. Do you have any alternative of assertion that I can make?

Couldn't it have another command it receives that runs the query on the database and returns the found records? Similar to what a full microservice application would have? Publisher gets a `getAll` request, sends a `getAll` command to the subscriber, subscriber runs to the database, fetches all, and returns, then the publisher returns to the client.

**Comment by malcolm-kee** [comment]
@jmcdo29  Thanks for the suggestion. I've removed the DB from the subscriber and make it respond to the publisher. Let me know if there is anything else doesn't seems right.

**Comment by jmcdo29** [comment]
I think I'll probably do a bit of cleanup in the future, but the fact that this is a working e2e test for microservices is a great the sake of an example. Thank you so much for all the help!

**Pull request merged**
