### PR TITLE
Update to latest recommended setup of PrismaService from NestJS docs

### PR DESCRIPTION
**Pull request by tak1n**
The docs for integrating Prisma into NestJS were adapted to no longer rely on `OnModuleDestroy`:

- https://docs.nestjs.com/recipes/prisma#use-prisma-client-in-your-nestjs-services
- https://github.com/nestjs/docs.nestjs.com/pull/1921

### CODE REVIEW

**Comment by jmcdo29** [comment]
Looks like even though the tests passed, something didn't exit properly, and the test errored out after 6 hours. @tak1n can you take a look?

**Comment by tak1n** [comment]
Yes will try to figure out whats going on ✌🏽

**Comment by tak1n** [comment]
Runnig with node version 14.17.6 locally I get following warning:
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.

Test Suites: 12 passed, 12 total
Tests:       34 passed, 34 total
Snapshots:   1 passed, 1 total
Time:        7.043 s
Ran all test suites.
```

Once I run the tests with `npm run test:e2e -- --detectOpenHandles` it just hangs. Adding a `--forceExit` lets it exit (still without reporting where the open handle is), but I do consider this a somewhat unsatisfying solution.

**Comment by tak1n** [comment]
Nvm got following open handle reported:
```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPSERVERWRAP

      20 | 
      21 |   it('/ (GET)', () => {
    > 22 |     return request(app.getHttpServer()).get('/').expect(200)
         |                                         ^
      23 |       .expect(`<!DOCTYPE html>
      24 | <html>
      25 |   <head>

      at Test.Object.<anonymous>.Test.serverAddress (node_modules/supertest/lib/test.js:61:33)
      at new Test (node_modules/supertest/lib/test.js:38:12)
      at Object.obj.<computed> [as get] (node_modules/supertest/index.js:27:14)
      at Object.<anonymous> (apps/render-sample/test/app.e2e-spec.ts:22:41)
```

**Comment by tak1n** [comment]
Adding `await prisma.$disconnect()` in the `afterAll` before `await app.close()` seems to fix it. Previously prisma disconnect was called through leveraging lifecycle events namely using `OnModuleDestroy`.

Should this be updated in the NestJS docs to point out disconnecting prisma from the db has to be done manually in tests? Or is there a better solution.

**Comment by jmcdo29** [comment]
Awesome, everything passed and is looking good! Thanks for the updates.

**Pull request merged**
