### PR TITLE
sample(graphql-sample): update version graphql

### PR DESCRIPTION
**Pull request by Tony133**
Update version graphql ✌️

### CODE REVIEW

**Comment by Tony133** [comment]
I think this mistake is not related to the PR I made

screenshot

right?

**Comment by jmcdo29** [comment]
Oh, shoot, I need to set up renovate instead of dependabot because of pnpm support. Run `pnpm install` locally to update the lockfile. POssibly remove the `pnpm-lock.yaml` first and try again to make sure it's fully up to date

**Comment by Tony133** [comment]
I did as you told me, now there is a new `pnpm-lock.yaml`, let's see what happens 🤞

**Comment by Tony133** [comment]
It worked!

**Pull request merged**
