### PR TITLE
chore: ci node version to 18 and 20

### PR DESCRIPTION
**Pull request by neerajkumar161**
- CI Node version updated to ```18x``` and ```20x``` from ```14x``` and ```16x```
- pnpm version updated from ```v6``` to ```v8```

### CODE REVIEW

**Comment by neerajkumar161** [comment]
@jmcdo29 one test case is failing after updating Node.js and pnpm. Can you please take a look?

**Comment by jmcdo29** [comment]
Looks like an error with socket.io. I'll have to debug further after some sleep

**Comment by jmcdo29** [comment]
Once I have #2005 merged in, this should be fixed and ready to go

**Comment by jmcdo29** [comment]
Actually, just realized 2005 will supersede this cause they need to go together. But this PR got me started on the right path of updating the node version so thank you for that!

**Comment by neerajkumar161** [comment]
> Actually, just realized 2005 will supersede this cause they need to go together. But this PR got me started on the right path of updating the node version so thank you for that!

It's my pleasure. I'm learning many things as well while contributing to the repo. So it's quite fun and challenging for me. :smile:

**Comment by neerajkumar161** [comment]
Closing the PR as this is fixed in #2005.

**Pull request closed without merging**
